Add banner section
maksim-dev1911/creative-agency-landing pull request #1
Opened 2022-07-18 11:32 UTC by maksim-dev1911

2022-07-18 13:53 UTC, edward-dev26 commented
А в общем огонь 🔥

2022-07-19 09:58 UTC, edward-dev26 requested changes

2022-07-19 09:58 UTC, edward-dev26 commented on src/index.html
> +                <p>Make your dream <br> business goal come true</p>
Лучше не использовать тег br вообще. Вместо этого лучше создай еще один p

2022-07-19 09:58 UTC, edward-dev26 commented on src/index.html
> +            <div class="about__aboutUs-text">
Придериживайся одного стиля наименованя класов. В данном случае лучше написать "about__head-text" или что то подобное

2022-07-19 09:58 UTC, edward-dev26 commented on src/scss/index.scss
> +    font-family: $font-quicksand;
Не нужно везде задавать font-family, если ты его задашь для body то он будет применятся для всех элементов

2022-07-19 09:58 UTC, edward-dev26 commented on src/scss/index.scss
> +        color: #1D1D1D;
Все цвета лучше вынести в переменные и назвать их как они названы в дизайне 
<img width="242" alt="Screenshot 2022-07-18 at 4 48 39 PM" src="https://user-images.githubusercontent.com/55874153/179525895-e1a120c5-7d2f-465e-8138-57086854e4da.png">

2022-07-19 09:58 UTC, edward-dev26 commented on src/scss/index.scss
> +    }
У тебя уже дублируются эти стили на 174 строчке. Это хорошая возможность создать миксин и использоваь его в этих местах

2022-07-19 10:03 UTC, maksim-dev1911 commented on src/index.html
> +                <p>Make your dream <br> business goal come true</p>
Готово

2022-07-19 10:04 UTC, maksim-dev1911 commented on src/index.html
> +            <div class="about__aboutUs-text">
Done

2022-07-19 11:31 UTC, maksim-dev1911 commented on src/scss/index.scss
> +    font-family: $font-quicksand;
Done

2022-07-19 11:31 UTC, maksim-dev1911 commented on src/scss/index.scss
> +        color: #1D1D1D;
Done

2022-07-19 12:54 UTC, edward-dev26 approved these changes

2022-07-19 12:54 UTC, merged